language: go
go:
  - 1.1
  - 1.2
  - 1.3
  - release
  - tip
install:
- go get github.com/mattcunningham/gumblr
before_install:
- openssl aes-256-cbc -K $encrypted_a64e0baf4f6a_key -iv $encrypted_a64e0baf4f6a_iv
  -in credentials_test.json.enc -out credentials_test.json -d
